version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.13         
    working_directory: ~/Quarkus-app/getting-started
    environment:
      MAVEN_OPTS: -Xmx6400m
    steps:
      ## Checkout the source code
      - checkout:
          path: ~/Quarkus-app
      - setup_remote_docker:
          docker_layer_caching: true # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run:
          name: Set Version
          command: |
                echo 'export VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)' >> $BASH_ENV
                echo $BASH_ENV
      - run:
          name: Build (MultiStage)
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker build -f src/main/docker/Dockerfile.multistage -t chihkang/quarkus-quickstart:${VERSION}-multistage .
              fi
          no_output_timeout: 30m
      - run:
          name: Docker Push (Native)
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                echo $DOCKER_PWD | docker login -u $DOCKER_USER --password-stdin               
                docker push chihkang/quarkus-quickstart:${VERSION}-multistage
                docker logout
            fi            